version: '3.7'

services:
  nginx:
    build:
      args:
        VERSION: $NGINX_VERSION
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: $APP_ENV
    image: $REGISTRY/cbh_nginx
    volumes:
      - ./assets:/app/public
    depends_on:
      - php-fpm
    ports:
      - 8000:80
  php-fpm:
    build:
      args:
        VERSION: $PHP_VERSION
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: $APP_ENV
    image: $REGISTRY/cbh_php-fpm
    volumes:
      - .:/app
    command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'
    depends_on:
      - mysql
  mysql:
    build:
      args:
        VERSION: $MYSQL_VERSION
      context: ./docker/mysql
    image: $REGISTRY/cbh_mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

